org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.daemon.jvm.options=-Xmx2048m
android.builtInKotlin=false
android.newDsl=false